# -*- coding: utf-8 -*-
"""批量填入 i18n-dict.json 的 en 字段（340 条英文翻译）。"""
import json, html, re, io

def norm(s):
    s = html.unescape(s)
    return re.sub(r'\s+', ' ', s).strip()

EN = {
    # ===== 短文案 284 条 =====
    "0 封闭不可调": "0 Closed, Non-Adjustable",
    "10 金属塑扣": "10 Metal Snap Clasp",
    "12 塑胶背扣": "12 Plastic Back Clasp",
    "24 金属日字扣": "24 Metal Bar Buckle",
    "30秒解决帽子皱纹。喷一喷，褶皱自然平复。": "Wrinkles gone in 30 seconds. Spray — creases smooth out on their own.",
    "ANTI-STATIC 除静电": "ANTI-STATIC De-Static",
    "CAP BRUSH 帽刷": "CAP BRUSH Cap Brush",
    "CAP CLEANING 水基清洁剂": "CAP CLEANING Water-Based Cleaner",
    "CAP CLEANING 清洁液": "CAP CLEANING Cap Cleaner",
    "CapTure · 棒球帽文化志": "CapTure · A Cap Culture Journal",
    "LZLD 独角兽": "LZLD Unicorn",
    "LZLD 独角兽 — SHER12": "LZLD Unicorn — SHER12",
    "LZLG 英斗狗": "LZLG Bulldog",
    "LZLG 英斗狗 — SHER12": "LZLG Bulldog — SHER12",
    "Love·栗色": "Love · Chestnut",
    "Love·栗色 — SHER12": "Love · Chestnut — SHER12",
    "Love·桃夭": "Love · Peach Bloom",
    "Love·桃夭 — SHER12": "Love · Peach Bloom — SHER12",
    "Love·竹青": "Love · Bamboo Green",
    "Love·竹青 — SHER12": "Love · Bamboo Green — SHER12",
    "MAODUN CAP GUARD 帽子防护剂": "MAODUN CAP GUARD Cap Protector",
    "Peace 乙0": "Peace Yi0",
    "Peace 乙0 — SHER12": "Peace Yi0 — SHER12",
    "Peace·墨": "Peace · Ink",
    "Peace·墨 — SHER12": "Peace · Ink — SHER12",
    "Peace·缥": "Peace · Pale Azure",
    "Peace·缥 — SHER12": "Peace · Pale Azure — SHER12",
    "Peace，全墨沉稳。": "Peace — all Ink, composed.",
    "Peace，蓝色款。和平的新表达。": "Peace — the blue edition. Peace, re-expressed.",
    "SHER 织带": "SHER Webbing",
    "Sher 乙0": "Sher Yi0",
    "Sher 乙0 — SHER12": "Sher Yi0 — SHER12",
    "Sher·月白天青": "Sher · Moon White & Sky Azure",
    "Sher·月白天青 — SHER12": "Sher · Moon White & Sky Azure — SHER12",
    "Sign 乙24H·苍": "Sign Yi24H · Pale Cyan",
    "Sign 乙24H·苍 — SHER12": "Sign Yi24H · Pale Cyan — SHER12",
    "Sign 乙24H·霁蓝": "Sign Yi24H · Clear Sky",
    "Sign 乙24H·霁蓝 — SHER12": "Sign Yi24H · Clear Sky — SHER12",
    "Sign 乙24H版，苍色低调。金属扣品质之选。": "Sign Yi24H in Pale Cyan — understated. The metal buckle, for those who care about quality.",
    "Sign 乙24H版，霁蓝清爽。金属扣品质之选。": "Sign Yi24H in Clear Sky — crisp. The metal buckle, for those who care about quality.",
    "Sign 系列海棠款，打破常规。": "Sign in Crabapple — breaking convention.",
    "Sign 系列茶色款，复古温暖。": "Sign in Tea — retro and warm.",
    "Sign 系列藤萝款，浪漫神秘。": "Sign in Wisteria — romantic and mysterious.",
    "Sign 系列黛绿款，沉静内敛。": "Sign in Jade Dark — calm and composed.",
    "Sign·海棠": "Sign · Crabapple",
    "Sign·海棠 — SHER12": "Sign · Crabapple — SHER12",
    "Sign·茶色": "Sign · Tea",
    "Sign·茶色 — SHER12": "Sign · Tea — SHER12",
    "Sign·藤萝": "Sign · Wisteria",
    "Sign·藤萝 — SHER12": "Sign · Wisteria — SHER12",
    "Sign·黛绿": "Sign · Jade Dark",
    "Sign·黛绿 — SHER12": "Sign · Jade Dark — SHER12",
    "Simple 基础系列，玄色配色。品质本身即是态度。": "Simple — Xuan Black. Quality is the attitude.",
    "Simple 基础系列，赭石配色。复古温暖，百搭之选。": "Simple — Ochre. Retro, warm, goes with everything.",
    "Simple·玄": "Simple · Xuan Black",
    "Simple·玄 — SHER12": "Simple · Xuan Black — SHER12",
    "Simple·赭石": "Simple · Ochre",
    "Simple·赭石 — SHER12": "Simple · Ochre — SHER12",
    "← 返回产品": "← Back to Products",
    "← 返回版型体系": "← Back to Fit System",
    "← 返回配件": "← Back to Accessories",
    "「中国」二字，金黄刺绣，酒红底。最直接的文化表达。": "\"China\" in gold embroidery on wine red. Culture, stated directly.",
    "「广东」刺绣，深圳人的广东认同。大湾区的心声。": "\"Guangdong\" embroidery — Shenzhen's Cantonese identity. The voice of the Greater Bay Area.",
    "「拾贰」刺绣，十二即一切。帽字十二笔，中国十二笔。": "\"Twelve\" embroidery — twelve is everything. \"Cap\" has 12 strokes; \"China\" has 12.",
    "一切": "Everything",
    "一只永远在加载懒惰的狗。不想起床、不想上班、永远在缓冲。": "A dog forever loading laziness. Won't get up, won't work, always buffering.",
    "丁": "Ding",
    "丁 · 瓜皮帽": "Ding · Melon Cap",
    "丁10 · 瓜皮帽": "Ding10 · Melon Cap",
    "丁·天青": "Ding · Sky Azure",
    "丁·天青 — SHER12": "Ding · Sky Azure — SHER12",
    "丁·玄": "Ding · Xuan Black",
    "丁·玄 — SHER12": "Ding · Xuan Black — SHER12",
    "上海": "Shanghai",
    "不服": "Unbowed",
    "不服 — SHER12": "Unbowed — SHER12",
    "丙": "Bing",
    "丙 · 渔夫帽": "Bing · Bucket Hat",
    "两个字，一种态度。戴上就是表态。": "Two words, one attitude. Wear it — that's the statement.",
    "中国·朱砂": "China · Cinnabar",
    "中国·朱砂 — SHER12": "China · Cinnabar — SHER12",
    "中国人自己的帽饰品牌": "A Chinese cap brand of our own",
    "中国帽子本土设计 · 做中国人自己的帽饰品牌": "Chinese caps, designed at home · A cap brand of our own",
    "主场": "Home Turf",
    "乙": "Yi",
    "乙 · 弯沿帽": "Yi · Curved-Brim Cap",
    "乙0 · 弯沿帽": "Yi0 · Curved-Brim Cap",
    "乙10 · 弯沿帽": "Yi10 · Curved-Brim Cap",
    "乙12 · 弯沿帽": "Yi12 · Curved-Brim Cap",
    "乙24 · 弯沿帽": "Yi24 · Curved-Brim Cap",
    "乙24H · 弯沿帽": "Yi24H · Curved-Brim Cap",
    "乙24S · 弯沿帽": "Yi24S · Curved-Brim Cap",
    "了解这个品牌": "About the Brand",
    "事": "Business",
    "五片帽天青款，SHER 刺绣点睛。可调节。": "5-panel cap in Sky Azure, finished with SHER embroidery. Adjustable.",
    "五片帽玄色款，可调节。版型定生死。": "5-panel cap in Xuan Black. Adjustable. Fit decides everything.",
    "五片平沿帽 · 甲10": "5-Panel Flat-Brim · Jia10",
    "产品": "Products",
    "你自己": "Yourself",
    "倒过来的和平。看不见的和平，才是真和平。": "Peace, turned upside down. The peace you can't see — that's real peace.",
    "免水洗 / 泡沫按压": "Water-Free / Foam Pump",
    "全部": "All",
    "公众号 CapTure_by_SHER12": "WeChat: CapTure_by_SHER12",
    "内衬": "Lining",
    "刷头": "Brush Head",
    "刺绣": "Embroidery",
    "力量": "Power",
    "功能": "Function",
    "加入 SHER12 CLUB": "Join SHER12 CLUB",
    "北京": "Beijing",
    "十二": "Twelve",
    "卡其 / 金绣": "Khaki / Gold Embroidery",
    "去毛屑 / 除尘": "Lint Removal / Dusting",
    "双面 · 渔夫帽": "Reversible · Bucket Hat",
    "双面天青赭石渔夫帽，一面天青一面赭石，两种心情。": "Reversible bucket — Sky Azure one side, Ochre the other. Two moods, one cap.",
    "双面桃夭月白渔夫帽，清新甜美。两面可穿。": "Reversible bucket in Peach Bloom & Moon White — fresh, sweet, wear either way.",
    "双面玄月白印花渔夫帽，SHER logo 醒目印花。": "Reversible bucket in Xuan Black & Moon White with a bold SHER print.",
    "可替换海绵刷头": "Replaceable Sponge Head",
    "名字": "Name",
    "向上": "Up",
    "品名": "Product Name",
    "品牌密码": "Brand Code",
    "图案": "Graphic",
    "图案系列": "Graphic Series",
    "地理系列": "Geo Series",
    "城市": "City",
    "城市系列": "City Series",
    "基础系列": "Simple Series",
    "墨": "Ink",
    "天青": "Sky Azure",
    "天青 / 赭石": "Sky Azure / Ochre",
    "头上": "Your Head",
    "定制、批发、联名合作，或者只是想认识一下——都欢迎。": "Custom, wholesale, collabs — or you just want to say hi. All welcome.",
    "家乡": "Hometown",
    "容量": "Volume",
    "小红书 @Sher12": "Xiaohongshu @Sher12",
    "已上线": "LIVE",
    "帽刷": "Cap Brush",
    "帽刷 — SHER12": "Cap Brush — SHER12",
    "帽型": "Silhouette",
    "平沿帽": "Flat-Brim Cap",
    "平沿帽 · 甲12": "Flat-Brim Cap · Jia12",
    "平沿帽 · 甲24": "Flat-Brim Cap · Jia24",
    "广东": "Guangdong",
    "广东 — SHER12": "Guangdong — SHER12",
    "广州": "Guangzhou",
    "弯沿帽": "Curved-Brim Cap",
    "弯沿帽 · 乙0": "Curved-Brim Cap · Yi0",
    "弯沿帽 · 乙10": "Curved-Brim Cap · Yi10",
    "弯沿帽 · 乙12": "Curved-Brim Cap · Yi12",
    "弯沿帽 · 乙24": "Curved-Brim Cap · Yi24",
    "弯沿帽 · 乙24H": "Curved-Brim Cap · Yi24H",
    "弯沿帽 · 乙24S": "Curved-Brim Cap · Yi24S",
    "弯沿帽配魔术贴，全玄百搭。可调节，随时到位。": "Curved-brim with Velcro — all Xuan Black, goes with everything. Adjustable, always on point.",
    "归属": "Belonging",
    "微信：sher12cap": "WeChat: sher12cap",
    "心声": "Voice",
    "心形 SHER · 12": "Heart SHER · 12",
    "心情": "Mood",
    "态度": "Attitude",
    "想亲手试戴？来深圳华侨城，我们寄售在一家叫「三分地」的店。": "Want to try them on? We stock at a shop called \"Sandian\" in Shenzhen OCT.",
    "憋着": "Hold In",
    "成都": "Chengdu",
    "我们的帽子": "Our Caps",
    "戴帽的人，自成江湖": "Caps on, we carve our own world",
    "戴帽的人，自成江湖。": "Caps on, we carve our own world.",
    "所有帽型": "All Silhouettes",
    "扣具": "Clasp",
    "把中国文化的图腾，一针一线绣在帽子上。": "Stitching Chinese cultural totems onto caps, thread by thread.",
    "拾贰": "Twelve",
    "拾贰 — SHER12": "Twelve — SHER12",
    "文化系列": "Culture Series",
    "更多 +": "More +",
    "更多款式": "More Styles",
    "更多配件": "More Accessories",
    "本能": "Instinct",
    "朱砂": "Cinnabar",
    "来了就是深圳人。": "Once you're here, you're a Shenzhener.",
    "查看全部丁型": "View All Type Ding",
    "查看全部丙型": "View All Type Bing",
    "查看全部乙型": "View All Type Yi",
    "查看全部甲型": "View All Type Jia",
    "查看系列": "View Series",
    "栗色": "Chestnut",
    "桃夭": "Peach Bloom",
    "棕": "Brown",
    "棕色 SHER 织带": "Brown SHER Webbing",
    "棕黄": "Tan",
    "每一座城市，都有属于自己的颜色与脾气。把城市戴在头上。": "Every city has its own color and temper. Wear it on your head.",
    "每一顶，都是为你做的": "Every cap, made for you",
    "水基温和去污": "Water-based, gentle cleaning",
    "波浪握持": "Wave-Grip Handle",
    "浅卡其": "Light Khaki",
    "浪漫": "Romance",
    "深圳": "Shenzhen",
    "深圳人": "Shenzhener",
    "清洁液": "Cap Cleaner",
    "清洁液 — SHER12": "Cap Cleaner — SHER12",
    "渔夫帽": "Bucket Hat",
    "渔夫帽 · 双面": "Bucket Hat · Reversible",
    "渔夫帽 · 魔术贴": "Bucket Hat · Velcro",
    "渔夫帽·天青赭石": "Bucket Hat · Sky Azure & Ochre",
    "渔夫帽·天青赭石 — SHER12": "Bucket Hat · Sky Azure & Ochre — SHER12",
    "渔夫帽·桃夭月白": "Bucket Hat · Peach Bloom & Moon White",
    "渔夫帽·桃夭月白 — SHER12": "Bucket Hat · Peach Bloom & Moon White — SHER12",
    "渔夫帽·玄月白": "Bucket Hat · Xuan Black & Moon White",
    "渔夫帽·玄月白 — SHER12": "Bucket Hat · Xuan Black & Moon White — SHER12",
    "灰": "Grey",
    "版型": "Fit",
    "版型体系": "Fit System",
    "版型体系 — SHER12": "Fit System — SHER12",
    "独角兽，糖果绿紫，甜美梦幻。潮玩 IP × 帽饰文化。": "Unicorn in candy green & purple — sweet and dreamy. Art-toy IP × cap culture.",
    "玄": "Xuan Black",
    "玄 / 白绣": "Xuan Black / White Embroidery",
    "珠峰": "Everest",
    "珠峰 — SHER12": "Everest — SHER12",
    "瓜皮帽": "Melon Cap",
    "瓜皮帽 · 丁10": "Melon Cap · Ding10",
    "生死": "Life or Death",
    "甲": "Jia",
    "甲 · 平沿帽": "Jia · Flat-Brim Cap",
    "甲10 · 五片平沿帽": "Jia10 · 5-Panel Flat-Brim",
    "甲12 · 平沿帽": "Jia12 · Flat-Brim Cap",
    "甲24 · 平沿帽": "Jia24 · Flat-Brim Cap",
    "甲乙丙丁 · 版型体系": "Jia Yi Bing Ding · The Fit System",
    "發财": "Fortune",
    "發财 — SHER12": "Fortune — SHER12",
    "白 / 灰蓝": "White / Grey Blue",
    "白蓝": "White / Blue",
    "真和平": "Real Peace",
    "立即了解": "Learn More",
    "竹青": "Bamboo Green",
    "米白 / 棕": "Cream / Brown",
    "米白 / 粉": "Cream / Pink",
    "米白 / 绿": "Cream / Green",
    "类型": "Type",
    "粉": "Pink",
    "粉 / 白": "Pink / White",
    "粉色 SHER 织带": "Pink SHER Webbing",
    "精神": "Spirit",
    "糖果绿紫": "Candy Green & Purple",
    "红 / 蓝": "Red / Blue",
    "线下购买 · 华侨城三分地": "Buy In-Store · OCT \"Sandian\"",
    "线下门店": "Store",
    "绿": "Green",
    "绿色 SHER 织带": "Green SHER Webbing",
    "缥": "Pale Azure",
    "翻译": "Translation",
    "聊聊？": "Wanna talk?",
    "联名系列": "Collab Series",
    "联系": "Contact",
    "自由": "Freedom",
    "藤萝紫": "Wisteria Purple",
    "蛇皮纹": "Snake Skin",
    "蛇皮纹 — SHER12": "Snake Skin — SHER12",
    "蛇皮纹理印花，红蓝撞色，野性十足。": "Snake-skin print with red-blue contrast — pure wild.",
    "街舞·甲24": "Street Dance · Jia24",
    "街舞·甲24 — SHER12": "Street Dance · Jia24 — SHER12",
    "街舞联名甲24版，平沿更贴街头。": "Street-dance collab, Jia24 fit — the flat brim stays true to the streets.",
    "设计": "Design",
    "赭石": "Ochre",
    "适用": "For",
    "配件": "Accessories",
    "配件专区": "Accessories",
    "配方": "Formula",
    "酒红 / 金绣": "Wine / Gold Embroidery",
    "野性": "Wild Side",
    "金 / 满印": "Gold / Full Print",
    "门店": "Shop",
    "除皱喷雾": "Wrinkle Spray",
    "青古绿": "Antique Green",
    "颜色": "Color",
    "香港": "Hong Kong, China",
    "马赛克SHER": "Mosaic SHER",
    "马赛克SHER — SHER12": "Mosaic SHER — SHER12",
    "马赛克像素风 SHER 印花，数字时代的帽饰表达。": "Pixelated mosaic SHER print — cap expression for the digital age.",
    "魔术贴 · 渔夫帽": "Velcro · Bucket Hat",
    "魔术贴·甲12": "Velcro · Jia12",
    "魔术贴·甲12 — SHER12": "Velcro · Jia12 — SHER12",
    "魔术贴可调节渔夫帽，玄色配色。功能与风格兼具。": "Velcro-adjustable bucket in Xuan Black — function meets style.",
    "魔术贴渔夫帽": "Velcro Bucket Hat",
    "魔术贴渔夫帽 — SHER12": "Velcro Bucket Hat — SHER12",
    "黑 / 白印花": "Black / White Print",
    "黑 / 白绣": "Black / White Embroidery",
    "查看系列 →": "View Series",
    "查看全部丁型 →": "View All Type Ding",
    "查看全部丙型 →": "View All Type Bing",
    "查看全部乙型 →": "View All Type Yi",
    "查看全部甲型 →": "View All Type Jia",
    "了解这个品牌 →": "About the Brand",

    # ===== 长文案 56 条 =====
    "十二即<span>一切</span>。": "Twelve is <span>everything</span>.",
    "<span>10 金属塑扣</span>": "<span>10 Metal Snap</span>",
    "版型，<br>定<span>生死</span>。": "The fit,<br>decides <span>everything</span>.",
    "向上，<br>永远<span>向上</span>。": "Up,<br>always <span>up</span>.",
    "爱，<br>不需要<span>翻译</span>。": "Love,<br>needs no <span>translation</span>.",
    "吼出来，<br>别<span>憋着</span>。": "Roar it out,<br>don't hold it <span>in</span>.",
    "签上，<br>你的<span>名字</span>。": "Sign it,<br>with your <span>name</span>.",
    "释放，<br>你的<span>野性</span>。": "Unleash,<br>your <span>wild side</span>.",
    "两个面，<br>两种<span>心情</span>。": "Two sides,<br>two <span>moods</span>.",
    "不服，<br>是一种<span>本能</span>。": "Unbowed,<br>is an <span>instinct</span>.",
    "广东，<br>是一种<span>归属</span>。": "Guangdong,<br>is a sense of <span>belonging</span>.",
    "做梦，<br>是认真的<span>事</span>。": "Dreaming,<br>is serious <span>business</span>.",
    "调节，<br>是一种<span>自由</span>。": "Adjustable,<br>is <span>freedom</span>.",
    "来了，<br>就是<span>深圳人</span>。": "Once you're here,<br>you're a <span>Shenzhener</span>.",
    "把「中国」<br>戴在<span>头上</span>。": "Wear \"China\"<br>on your <span>head</span>.",
    "街舞与帽，<br>同一种<span>态度</span>。": "Street dance and caps —<br>the same <span>attitude</span>.",
    "少即是多，<br>简单即是<span>力量</span>。": "Less is more —<br>simplicity is <span>power</span>.",
    "像素，<br>是数字时代的<span>浪漫</span>。": "Pixels,<br>the <span>romance</span> of the digital age.",
    "看不见的和平，<br>才是<span>真和平</span>。": "Peace you can't see,<br>is <span>real peace</span>.",
    "30秒解决帽子皱纹。喷一喷，褶皱自然平复。帽子常备，出行无忧。": "Wrinkles gone in 30 seconds. Spray — creases smooth out on their own. Keep one on hand wherever you go.",
    "Sher 乙0版，封闭帽型。KEEP THE HEAD UP。": "Sher Yi0 — a closed silhouette. KEEP THE HEAD UP.",
    "42款帽子。从文化到联名，从平沿帽到弯沿帽——总有一顶属于你。": "42 caps. From culture to collabs, flat-brim to curved — one of them is yours.",
    "为什么是<span class=\"hl\">十二</span>？": "Why <span class=\"hl\">twelve</span>?",
    "帽子干净了，<br>整个人都<span>精神</span>了。": "A clean cap,<br>a <span>sharper</span> you.",
    "弯沿 Peace 乙0版，封闭帽型，不可调节。和平的另一种形态。": "Curved-brim Peace Yi0 — closed, non-adjustable. Peace in another form.",
    "向上，永远向上。8848.86m，一座山的高度，一种态度的高度。": "Up, always up. 8848.86m — the height of a mountain, the height of an attitude.",
    "倒过来的和平。看不见的和平，才是真和平。墨与缥，两种安静的姿态。": "Peace, turned upside down. The peace you can't see is the real peace. Ink and Pale Azure — two quiet gestures.",
    "爱惜你的帽子，<br>就是爱惜<span>你自己</span>。": "Take care of your cap,<br>and you take care of <span>yourself</span>.",
    "📍 深圳市南山区华侨城创意文化园南区F1栋101E · 三分地印象": "📍 101E, F1, OCT-LOFT South, Nanshan District, Shenzhen · \"Sandian\"",
    "CAP CLEANING 免水洗帽子清洁液。200ml 泡沫按压。": "CAP CLEANING — water-free cap cleaner. 200ml foam pump.",
    "港澳人的心声，<br>也是中国人的<span>心声</span>。": "The voice of Hong Kong and Macao,<br>is the <span>voice</span> of China.",
    "好帽要养。帽刷 + 清洁液 + 除皱喷雾，让你的帽子一直像新的一样。": "Good caps need care. Brush + cleaner + wrinkle spray — keep every cap looking new.",
    "我们用一套自己的语言定义帽子。四种帽型，四种扣法，比数字编号更懂中国人。": "We define caps in our own language. Four silhouettes, four clasps — a system that gets Chinese wearers better than any number code.",
    "线下试戴 · 深圳市南山区华侨城创意文化园南区F1栋101E 三分地印象": "Try On In-Store · 101E, F1, OCT-LOFT South, Nanshan, Shenzhen — \"Sandian\"",
    "棒球帽专用去毛屑刷。可替换海绵刷头，波浪握持设计。轻轻一刷，毛屑灰尘全走。": "A lint brush made for caps. Replaceable sponge head, wave-grip handle. One light sweep — lint and dust gone.",
    "CAP BRUSH 棒球帽专用去毛屑刷。KEEP THE HEAD UP。": "CAP BRUSH — the lint brush for caps. KEEP THE HEAD UP.",
    "「中国」二字，金黄刺绣，酒红底；不服两个字，一种态度。把中国文化，戴在头上。": "\"China\" in gold embroidery on wine red; \"Unbowed\" — two words, one attitude. Wear Chinese culture on your head.",
    "<span>10 金属塑扣</span><span>0 封闭不可调</span>": "<span>10 Metal Snap</span><span>0 Closed</span>",
    "<span>24 金属日字扣</span><span>0 封闭不可调</span>": "<span>24 Metal Bar Buckle</span><span>0 Closed</span>",
    "<span>24 金属日字扣</span><span>12 塑胶背扣</span>": "<span>24 Metal Bar Buckle</span><span>12 Plastic Clasp</span>",
    "免水洗帽子清洁液。200ml泡沫按压，温和去污不伤帽型。按一按，擦一擦，帽子焕新。": "Water-free cap cleaner. 200ml foam pump — cleans gently without ruining the shape. Pump, wipe, fresh again.",
    "免水洗帽子清洁液。200ml 泡沫按压，温和去污不伤帽型。按一按，擦一擦，帽子焕新。": "Water-free cap cleaner. 200ml foam pump — cleans gently without ruining the shape. Pump, wipe, fresh again.",
    "扣型编码：12 塑胶背扣 · 24 金属日字扣 · 0 封闭不可调 · 10 金属塑扣": "Clasp Code: 12 plastic back clasp · 24 metal bar buckle · 0 closed, non-adjustable · 10 metal snap clasp",
    "Sher 系列月白天青配色，清爽街头风。月白帽身搭配天青帽檐，手写体 Sher logo。": "Sher in Moon White & Sky Azure — clean street style. Moon-white crown, sky-azure brim, hand-written Sher logo.",
    "SHER12 不只是一顶帽子。是一群相信「中国设计能上头」的人。加进来，第一时间收到每一次发售。": "SHER12 is more than a cap. We're a crew who believe Chinese design deserves a place on your head. Join us — be first to know about every drop.",
    "绿色帽身+白色大字「發」覆盖全帽，帽檐下印「生财有道」。这顶帽子藏了一句脏话，但只有你自己知道。": "Green crown, white \"發\" across the cap; under the brim: \"生财有道\". This cap hides a swear word — but only you know it.",
    "心形 SHER 刺绣，粉色帽檐。Love 系列——爱不需要翻译，戴上就是表态。三色可选：桃夭、栗色、竹青。": "Heart SHER embroidery, pink brim. The Love series — love needs no translation; wearing it is the statement. Three colors: Peach Bloom, Chestnut, Bamboo Green.",
    "Sher = Shen（深圳）+ er（人）&nbsp;&nbsp;·&nbsp;&nbsp;<b>来了就是深圳人。</b>": "Sher = Shen (Shenzhen) + er (person) &nbsp;&nbsp;·&nbsp;&nbsp;<b>Once you're here, you're a Shenzhener.</b>",
    "米白帽身，棕色帽檐。正面心形 SHER 刺绣，侧面棕色 12 标志。银色金属日字扣，扣心 12。内衬棕色 SHER 交叉织带。": "Cream crown, brown brim. Heart SHER embroidery up front, brown 12 on the side. Silver metal bar buckle with 12 at the clasp. Brown SHER cross-webbing lining.",
    "米白帽身，绿色帽檐。正面心形 SHER 刺绣，侧面绿色 12 标志。银色金属日字扣，扣心 12。内衬绿色 SHER 交叉织带。": "Cream crown, green brim. Heart SHER embroidery up front, green 12 on the side. Silver metal bar buckle with 12 at the clasp. Green SHER cross-webbing lining.",
    "米白帽身，粉色帽檐。正面心形 SHER 刺绣，侧面粉色 12 标志。银色金属日字扣，扣心 12。内衬粉色 SHER 交叉织带。": "Cream crown, pink brim. Heart SHER embroidery up front, pink 12 on the side. Silver metal bar buckle with 12 at the clasp. Pink SHER cross-webbing lining.",
    "<span class=\"dot\" style=\"background:#6B8E5A\"></span><span class=\"cn\">绿</span>": "<span class=\"dot\" style=\"background:#6B8E5A\"></span><span class=\"cn\">Green</span>",
    "<span class=\"dot\" style=\"background:#8B6F4E\"></span><span class=\"cn\">棕</span>": "<span class=\"dot\" style=\"background:#8B6F4E\"></span><span class=\"cn\">Brown</span>",
    "<span class=\"dot\" style=\"background:#F4B8C8\"></span><span class=\"cn\">粉</span>": "<span class=\"dot\" style=\"background:#F4B8C8\"></span><span class=\"cn\">Pink</span>",
    "「帽」字<b>十二</b>笔，「中国」也是<b>十二</b>笔。<br>\n      一天<b>十二</b>个时辰，一年<b>十二</b>个月。<br>\n      不是随便挑的数字——是刻在中国文化里的密码。": "The character \"帽\" has <b>12</b> strokes, and so does \"中国\".<br>\n      <b>12</b> hours make a day cycle, <b>12</b> months make a year.<br>\n      Not a random number — a code carved into Chinese culture.",
    "<span class=\"cl\">ANTI-STATIC 除静电</span><span class=\"cl\">MAODUN CAP GUARD 帽子防护剂</span><span class=\"cl\">CAP CLEANING 水基清洁剂</span><span class=\"cl\">帽刷</span>": "<span class=\"cl\">ANTI-STATIC De-Static</span><span class=\"cl\">MAODUN CAP GUARD Cap Protector</span><span class=\"cl\">CAP CLEANING Water-Based Cleaner</span><span class=\"cl\">Cap Brush</span>",
}

path = 'i18n-dict.json'
with io.open(path, encoding='utf-8') as f:
    d = json.load(f)

# 关键修复：EN 键也要先 norm，再作为查找表（否则含 &nbsp;/换行的键匹配不上）
EN_NORM = {norm(k): v for k, v in EN.items()}

missing = []
filled = 0
for k, v in d.items():
    nk = norm(k)
    if nk in EN_NORM:
        v['en'] = EN_NORM[nk]
        filled += 1
    else:
        missing.append(k)

with io.open(path, 'w', encoding='utf-8') as f:
    json.dump(d, f, ensure_ascii=False, indent=2)

print('filled: %d / %d' % (filled, len(d)))
if missing:
    print('MISSING %d:' % len(missing))
    for k in missing:
        print('  MISSING:', repr(k))
